[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
env_logger = "0.11"
eyre = "0.6"
log = "0.4"
pollster = "0.4"
rodio = "0.19"
wgpu = "28"
winit = "0.30.8"

[workspace.lints.rust]
dead_code = "allow"
